import Head from 'next/head'
import dynamic from 'next/dynamic'

const RemoteAbout = dynamic(() => import("aboutApp/about"), { ssr: false })

const AboutPage = () => {
  return (
    <>
      <Head>
        <title>Host MFE | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RemoteAbout />
    </>
  )
}

export default AboutPage
