import Head from 'next/head'

import Header from '../src/components/header'
import Nav from '../src/components/nav'

export default function Home() {
  return (
    <>
      <Head>
        <title>Host MFE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Nav />
    </>
  )
}
